mappings:
  FAQPage: ilateral\SilverStripe\Support\Model\FAQPage
  QandAPage: ilateral\SilverStripe\Support\Model\QandAPage
  FeedbackItem: ilateral\SilverStripe\Support\Model\FeedbackItem
  FAQPage_Controller: ilateral\SilverStripe\Support\Control\FAQPageController
  QandAPage_Controller: ilateral\SilverStripe\Support\Control\QandAPageController
