mappings:
  FAQPage: DFT\SilverStripe\FAQPages\Model\FAQPage
  QandAPage: DFT\SilverStripe\FAQPages\Model\QandAPage
  FeedbackItem: DFT\SilverStripe\FAQPages\Model\FeedbackItem
  FAQPage_Controller: DFT\SilverStripe\FAQPages\Control\FAQPageController
  QandAPage_Controller: DFT\SilverStripe\FAQPages\Control\QandAPageController
